[package]
name = "coin_metadata"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
#published-at = "0xd28d89ef5a541b77418cd046b21ffa59956cea474906b83deaa7c9002f914406"

[dependencies]
SuiSystem={git ="https://github.com/hellokittyboy-code/obc", subdir ="crates/sui-framework/packages/sui-system", rev="develop_v1.2.0_treasury"}
MoveStdlib ={git ="https://github.com/hellokittyboy-code/obc", subdir ="crates/sui-framework/packages/move-stdlib", rev="develop_v1.2.0_treasury"}

[addresses]
coin_metadata = "0x0"