[package]
name = "coin_metadata"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
published-at = "0x07bf8252f080ac6d5db06c267040a84a74b6db8fc9b0e3042bf33de97a82a5b5"

[dependencies]
SuiSystem={git ="https://github.com/hellokittyboy-code/obc", subdir ="crates/sui-framework/packages/sui-system", rev="develop_v1.24.0_4_test"}
MoveStdlib ={git ="https://github.com/hellokittyboy-code/obc", subdir ="crates/sui-framework/packages/move-stdlib", rev="develop_v1.24.0_4_test"}

[addresses]
coin_metadata = "0x0"